/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;


import clases.Bovino;
import clases.Enfermedad;
import clases.Padece;
import clases.Tratamiento;
import dominio.dControladora;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author nico_
 */
public class frmFechaFinalizacionTratamiento extends javax.swing.JFrame {

    public frmFechaFinalizacionTratamiento() {
        initComponents();
        //setExtendedState(MAXIMIZED_BOTH); // Maximisa la ventana 
        this.setTitle("FECHA FINALIZACIÓN TRATAMIENTO");
        lblRFechaFT.setVisible(false);

        int idTratamiento = frmTratamiento.idTratamiento;
        Tratamiento tratamiento = dControladora.buscarTratamiento(idTratamiento);
        Bovino bovino = dControladora.buscarBovinoId(tratamiento.getPadece().getIdBovino());
        Enfermedad enfermedad = dControladora.buscarEnfermedad(tratamiento.getPadece().getIdEnfermedad());

        lblCaravana.setText(bovino.getCaravanaBovino());
        lblEnfermedadT.setText(enfermedad.getNombre());
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        String fechaDate = formato.format(tratamiento.getFechaInicio());
        lblFechaInicioT.setText(fechaDate);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotones = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jDateFechaFinalizacionT = new com.toedter.calendar.JDateChooser();
        btnConfirmar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblFechaInicioT = new javax.swing.JLabel();
        lblCaravana = new javax.swing.JLabel();
        lblEnfermedadT = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        lblRFechaFT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jDateFechaFinalizacionT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 160, 30));

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmarMouseClicked(evt);
            }
        });
        jPanel2.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 90, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Fecha Finalización de Tratamiento:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Fecha Inicio Tratamiento:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 150, 20));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Bovino:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 50, 20));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Enfermedad:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 80, 20));

        lblFechaInicioT.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblFechaInicioT.setForeground(new java.awt.Color(0, 0, 0));
        lblFechaInicioT.setText("...");
        jPanel2.add(lblFechaInicioT, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 100, 20));

        lblCaravana.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblCaravana.setForeground(new java.awt.Color(0, 0, 0));
        lblCaravana.setText("...");
        jPanel2.add(lblCaravana, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 90, 20));

        lblEnfermedadT.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblEnfermedadT.setForeground(new java.awt.Color(0, 0, 0));
        lblEnfermedadT.setText("...");
        jPanel2.add(lblEnfermedadT, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 80, 20));

        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 90, 30));

        lblRFechaFT.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblRFechaFT.setForeground(new java.awt.Color(0, 0, 0));
        lblRFechaFT.setText("Requerido");
        jPanel2.add(lblRFechaFT, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 70, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 400, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean validarCampos() {

        int contador = 0;

        if (jDateFechaFinalizacionT.getDate() == null) {
            lblRFechaFT.setVisible(true);
            contador++;
        } else {
            lblRFechaFT.setVisible(false);
        }

        if (contador < 1) {
            return true;
        } else {
            return false;
        }
    }

    public void limpiarCajas() {

        jDateFechaFinalizacionT.setDate(null);

    }


    private void btnConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarMouseClicked

        if (validarCampos()) {

            int idTratamiento = frmTratamiento.idTratamiento;
            Tratamiento t = dControladora.buscarTratamiento(idTratamiento);
            
            Padece padece = new Padece(t.getPadece().getIdEnfermedad(), t.getPadece().getIdBovino(), t.getPadece().getFechaInicio(), t.getPadece().getFechaFinalizacion());

            Date fechaF = jDateFechaFinalizacionT.getDate();

            Tratamiento tratamientoNuevo = new Tratamiento(t.getIdTratamiento(),padece, t.getDetalle(), t.getFechaInicio(), fechaF);

            try {
                
                 boolean resultado = dControladora.modificarTratamientoFechaFin(tratamientoNuevo);
                if (resultado) {

                    JOptionPane.showMessageDialog(null, "Se Ingreso Correctamente la Fecha de Finalización ");

                    frmTratamiento.frmTratamiento1.dispose();
                    frmTratamiento.frmTratamiento1 = null;

                    frmTratamiento fTratamiento = new frmTratamiento();
                    fTratamiento.setVisible(true);
                    this.dispose();

                } else {
                    JOptionPane.showMessageDialog(null, "Error: No se pudo ingresar la Fecha de Finalización ");

                    frmTratamiento fTratamiento = new frmTratamiento();
                    fTratamiento.actualizarTabla();
                    this.dispose();
                }

            } catch (Exception e) {
                throw e;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese los datos faltantes");
        }

    }//GEN-LAST:event_btnConfirmarMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        
        this.dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFechaFinalizacionTratamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFechaFinalizacionTratamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFechaFinalizacionTratamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFechaFinalizacionTratamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFechaFinalizacionTratamiento().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.ButtonGroup grupoBotones;
    private com.toedter.calendar.JDateChooser jDateFechaFinalizacionT;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCaravana;
    private javax.swing.JLabel lblEnfermedadT;
    private javax.swing.JLabel lblFechaInicioT;
    private javax.swing.JLabel lblRFechaFT;
    // End of variables declaration//GEN-END:variables
}
