/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import clases.Hembra;
import clases.Produccion;
import dominio.dControladora;
import java.util.Date;
import javax.swing.JOptionPane;
import static presentacion.frmModificarProduccion.caravana;

/**
 *
 * @author nico_
 */
public class frmModificarProduccion extends javax.swing.JInternalFrame {

      public static String caravana = null;
      
    /**
     * Creates new form frmModificarProduccion1
     */
    public frmModificarProduccion() {
        initComponents();
        
        this.setSize(frmInicio.jDkPEscritorio.getWidth(), frmInicio.jDkPEscritorio.getHeight()); 
        this.setTitle("MODIFICAR PRODUCCION DE LECHE MENSUAL");
        lblRCaravanaH.setVisible(false);
        lblRFechaProduccion.setVisible(false);
        lblRPrimeraProduccion.setVisible(false);
        lblRSegundaProduccion.setVisible(false);
        lblRProteinas.setVisible(false);
        lblRGrasas.setVisible(false);
        lblRCelulasSomaticas.setVisible(false);
        
        Produccion produccion = dControladora.buscarProduccion(frmProduccion.idProduccion);
        
        if(caravana != null){
            txtModificarCaravanaH.setText(caravana);
        }else{
            txtModificarCaravanaH.setText(produccion.getHembra().getCaravanaBovino());
        }
        jDateModificarFechaP.setDate(produccion.getFecha());
        txtModificarPrimeraP.setText(produccion.getPrimeraProduccion().toString());
        txtModificarSegundaP.setText(produccion.getSegundaProduccion().toString());
        txtModificarProteinas.setText(produccion.getProteina().toString());
        txtModificarGrasas.setText(produccion.getGrasa().toString());
        txtModificarCS.setText(Integer.toString(produccion.getCelulaSomatica()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtModificarSegundaP = new javax.swing.JTextField();
        jDateModificarFechaP = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        btnModificarProduccion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtModificarCaravanaH = new javax.swing.JTextField();
        txtModificarGrasas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtModificarPrimeraP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtModificarCS = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtModificarProteinas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lblRCelulasSomaticas = new javax.swing.JLabel();
        lblRCaravanaH = new javax.swing.JLabel();
        lblRFechaProduccion = new javax.swing.JLabel();
        lblRPrimeraProduccion = new javax.swing.JLabel();
        lblRSegundaProduccion = new javax.swing.JLabel();
        lblRGrasas = new javax.swing.JLabel();
        lblRProteinas = new javax.swing.JLabel();
        btnBuscarBovino = new javax.swing.JButton();

        setBackground(new java.awt.Color(54, 67, 114));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBackground(new java.awt.Color(133, 146, 158));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Segunda Produccion (lts):");

        jLabel4.setText("Fecha Produccion:");

        btnModificarProduccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar16px.png"))); // NOI18N
        btnModificarProduccion.setText("Modificar");
        btnModificarProduccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarProduccionMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Caravana:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Grasas:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Primera Produccion (lts):");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Celulas Somaticas:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Proteinas:");

        lblRCelulasSomaticas.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblRCelulasSomaticas.setForeground(new java.awt.Color(0, 0, 0));
        lblRCelulasSomaticas.setText("Requerido");

        lblRCaravanaH.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblRCaravanaH.setForeground(new java.awt.Color(0, 0, 0));
        lblRCaravanaH.setText("Requerido");

        lblRFechaProduccion.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblRFechaProduccion.setForeground(new java.awt.Color(0, 0, 0));
        lblRFechaProduccion.setText("Requerido");

        lblRPrimeraProduccion.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblRPrimeraProduccion.setForeground(new java.awt.Color(0, 0, 0));
        lblRPrimeraProduccion.setText("Requerido");

        lblRSegundaProduccion.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblRSegundaProduccion.setForeground(new java.awt.Color(0, 0, 0));
        lblRSegundaProduccion.setText("Requerido");

        lblRGrasas.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblRGrasas.setForeground(new java.awt.Color(0, 0, 0));
        lblRGrasas.setText("Requerido");

        lblRProteinas.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblRProteinas.setForeground(new java.awt.Color(0, 0, 0));
        lblRProteinas.setText("Requerido");

        btnBuscarBovino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar16px.png"))); // NOI18N
        btnBuscarBovino.setText("Buscar");
        btnBuscarBovino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarBovinoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtModificarCS, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lblRCelulasSomaticas))
                    .addComponent(btnModificarProduccion)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtModificarCaravanaH, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnBuscarBovino))
                            .addComponent(lblRCaravanaH)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtModificarPrimeraP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(lblRPrimeraProduccion))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtModificarProteinas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblRProteinas)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jDateModificarFechaP, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(lblRFechaProduccion))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtModificarSegundaP, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblRSegundaProduccion))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtModificarGrasas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblRGrasas))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtModificarCaravanaH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarBovino, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblRCaravanaH)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtModificarPrimeraP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblRPrimeraProduccion)))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRProteinas)
                            .addComponent(txtModificarProteinas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateModificarFechaP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblRFechaProduccion)))
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtModificarSegundaP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRSegundaProduccion))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRGrasas)
                            .addComponent(txtModificarGrasas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtModificarCS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblRCelulasSomaticas)))
                .addGap(40, 40, 40)
                .addComponent(btnModificarProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean validarCampos() {

        int contador = 0;
        if (txtModificarCaravanaH.getText().equals("")){lblRCaravanaH.setVisible(true);contador++;} else {lblRCaravanaH.setVisible(false);}
        if (jDateModificarFechaP.getDate() == null){lblRFechaProduccion.setVisible(true);contador++;} else{lblRFechaProduccion.setVisible(false);}
        if (txtModificarPrimeraP.getText().equals("")){lblRPrimeraProduccion.setVisible(true); contador++;}else{lblRPrimeraProduccion.setVisible(false);}
        if (txtModificarSegundaP.getText().equals("")){lblRSegundaProduccion.setVisible(true);contador++;} else{lblRSegundaProduccion.setVisible(false);}
        if (txtModificarProteinas.getText().equals("")){lblRProteinas.setVisible(true);contador++;} else{lblRProteinas.setVisible(false);}
        if (txtModificarGrasas.getText().equals("")){lblRGrasas.setVisible(true);contador++;} else{lblRGrasas.setVisible(false);}
        if (txtModificarCS.getText().equals("")){lblRCelulasSomaticas.setVisible(true);contador++;} else{lblRCelulasSomaticas.setVisible(false);}

        if (contador < 1) {
            return true;
        } else {
            return false;
        }
    }
    
    public void limpiarCajas() {

        txtModificarCaravanaH.setText(null);
        txtModificarSegundaP.setText(null);
        jDateModificarFechaP.setDate(null);
        txtModificarPrimeraP.setText(null);
        txtModificarSegundaP.setText(null);
        txtModificarProteinas.setText(null);
        txtModificarGrasas.setText(null);
        txtModificarCS.setText(null);

    }
    
    private void btnModificarProduccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarProduccionMouseClicked

        if(validarCampos()){
            Produccion produccion = dControladora.buscarProduccion(frmProduccion.idProduccion);

            String carvana = txtModificarCaravanaH.getText();
            Hembra hembra = dControladora.buscarHembraPorCaravana(carvana);
            Date fecha  = jDateModificarFechaP.getDate();
            Double primeraP = Double.parseDouble(txtModificarPrimeraP.getText());
            Double segundaP = Double.parseDouble(txtModificarSegundaP.getText());
            Double proteinas = Double.parseDouble(txtModificarProteinas.getText());
            Double grasas = Double.parseDouble(txtModificarGrasas.getText());
            int celulasSomaticas = Integer.parseInt(txtModificarCS.getText());

            Produccion produccionNueva = new Produccion(produccion.getIdProduccion(),primeraP,segundaP,produccion.getProduccionTotal(),proteinas,grasas,celulasSomaticas,fecha,hembra);

            try {

                if (dControladora.modificarProduccion(produccionNueva)) {

                    JOptionPane.showMessageDialog(null, "Producción Modificada Correctamente");
                    caravana = null;
                    limpiarCajas(); // Limpiamos Caja de Texto

                    this.dispose();
                    frmProduccion nuevoFormulario = new frmProduccion();
                     frmInicio.jDkPEscritorio.add(nuevoFormulario);
                    nuevoFormulario.setVisible(true);                 

                } else {
                    JOptionPane.showMessageDialog(null, "Error: No se pudo Modificar la Producción");
                }
            } catch (Exception e) {
                throw e;
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Ingrese los datos faltantes");
        }

    }//GEN-LAST:event_btnModificarProduccionMouseClicked

    private void btnBuscarBovinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarBovinoMouseClicked

        frmBuscarHembra buscarHembra = new frmBuscarHembra();
        frmBuscarHembra.frm = "frmModificarProduccion";
        buscarHembra.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBuscarBovinoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarBovino;
    private javax.swing.JButton btnModificarProduccion;
    private com.toedter.calendar.JDateChooser jDateModificarFechaP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblRCaravanaH;
    private javax.swing.JLabel lblRCelulasSomaticas;
    private javax.swing.JLabel lblRFechaProduccion;
    private javax.swing.JLabel lblRGrasas;
    private javax.swing.JLabel lblRPrimeraProduccion;
    private javax.swing.JLabel lblRProteinas;
    private javax.swing.JLabel lblRSegundaProduccion;
    private javax.swing.JTextField txtModificarCS;
    private javax.swing.JTextField txtModificarCaravanaH;
    private javax.swing.JTextField txtModificarGrasas;
    private javax.swing.JTextField txtModificarPrimeraP;
    private javax.swing.JTextField txtModificarProteinas;
    private javax.swing.JTextField txtModificarSegundaP;
    // End of variables declaration//GEN-END:variables
}
