/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;


import clases.Bovino;
import clases.Enfermedad;
import clases.EstadoBovino;
import clases.EstadoDelBovino;
import clases.Padece;
import dominio.dControladora;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import persistencia.pEnfermedad;
import persistencia.pEstadoDelBovino;

/**
 *
 * @author nico_
 */
public class frmModificarEstadoConBovino extends javax.swing.JFrame {

    public static String caravana = null;

    public frmModificarEstadoConBovino() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH); // Maximisa la ventana 
        this.setTitle("MODIFICAR ESTADO DEL BOVINO");
        lblRCaravanaB.setVisible(false);
        lblRFechaInicioE.setVisible(false);
        lblREstado.setVisible(false);
        llenarComboEstado();
        
        
        if (caravana != null) {
            txtModificarCaravanaBovino.setText(caravana);
        } else {
            txtModificarCaravanaBovino.setText(frmEstadoConBovino.caravana);
        }

        EstadoBovino estadoBovino = frmEstadoConBovino.estadoBovino;
        
        jDateModificarFechaIE.setDate(estadoBovino.getFechaInicio());
        Date fechaIE = jDateModificarFechaIE.getDate();
        jDateModificarFechaFE.setDate(estadoBovino.getFechaFinalizacion());
        Date fechaFE = jDateModificarFechaFE.getDate();
        int idEstado = estadoBovino.getIdEstadoDelBovino();
        EstadoDelBovino estadoDelBovino = dControladora.buscarEstadoDelBovino(idEstado); 
        
        cboModificarEstado.getModel().setSelectedItem(estadoDelBovino);
        cboModificarEstado.setSelectedItem(estadoDelBovino);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotones = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jDateModificarFechaIE = new com.toedter.calendar.JDateChooser();
        jDateModificarFechaFE = new com.toedter.calendar.JDateChooser();
        txtModificarCaravanaBovino = new javax.swing.JTextField();
        btnBuscarBovino = new javax.swing.JButton();
        lblRCaravanaB = new javax.swing.JLabel();
        lblRFechaInicioE = new javax.swing.JLabel();
        lblREstado = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cboModificarEstado = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Caravana:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 160, -1));
        jPanel2.add(jDateModificarFechaIE, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 160, 30));
        jPanel2.add(jDateModificarFechaFE, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 160, 30));

        txtModificarCaravanaBovino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtModificarCaravanaBovinoKeyReleased(evt);
            }
        });
        jPanel2.add(txtModificarCaravanaBovino, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 100, 30));

        btnBuscarBovino.setText("Buscar");
        btnBuscarBovino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarBovinoMouseClicked(evt);
            }
        });
        jPanel2.add(btnBuscarBovino, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        lblRCaravanaB.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblRCaravanaB.setForeground(new java.awt.Color(0, 0, 0));
        lblRCaravanaB.setText("Requerido");
        jPanel2.add(lblRCaravanaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 120, 20));

        lblRFechaInicioE.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblRFechaInicioE.setForeground(new java.awt.Color(0, 0, 0));
        lblRFechaInicioE.setText("Requerido");
        jPanel2.add(lblRFechaInicioE, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 120, 20));

        lblREstado.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblREstado.setForeground(new java.awt.Color(0, 0, 0));
        lblREstado.setText("Requerido");
        jPanel2.add(lblREstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 120, 20));

        btnModificar.setText("Modificar");
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
        });
        jPanel2.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 90, -1));

        jLabel8.setText("Estado:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel9.setText("Fecha Finalizacion de Estado:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        cboModificarEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        jPanel2.add(cboModificarEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 180, 30));

        jLabel4.setText("Fecha Comienzo de Estado:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 550, 330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean validarCampos() {

        int contador = 0;
        if (txtModificarCaravanaBovino.getText().equals("")) {
            lblRCaravanaB.setVisible(true);
            contador++;
        } else {
            lblRCaravanaB.setVisible(false);
        }
        if (jDateModificarFechaIE.getDate() == null) {
            lblRFechaInicioE.setVisible(true);
            contador++;
        } else {
            lblRFechaInicioE.setVisible(false);
        }
        if (cboModificarEstado.getSelectedIndex() == 0) {
            lblREstado.setVisible(true);
            contador++;
        } else {
            lblREstado.setVisible(false);
        }

        if (contador < 1) {
            return true;
        } else {
            return false;
        }
    }

    public void limpiarCajas() {

        txtModificarCaravanaBovino.setText(null);
        jDateModificarFechaIE.setDate(null);
        jDateModificarFechaFE.setDate(null);
        cboModificarEstado.setSelectedIndex(0);

    }

    private void llenarComboEstado() {

        ArrayList<EstadoDelBovino> listaEstados = pEstadoDelBovino.listarEstadosDelBovino();

        for (EstadoDelBovino estado : listaEstados) {

            cboModificarEstado.addItem(estado);
        }

    }

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked

        if (validarCampos()) {
            
            EstadoBovino estadoBovino = frmEstadoConBovino.estadoBovino;
            
            String caravanaVieja = frmEstadoConBovino.caravana;
            Bovino bovinoViejo = dControladora.buscarBovinoCaravana(caravanaVieja);
            Date fechaIEVieja = estadoBovino.getFechaInicio();
            Date fechaFEVieja = estadoBovino.getFechaFinalizacion();
            EstadoDelBovino estadoViejo = dControladora.buscarEstadoDelBovino(estadoBovino.getIdEstadoDelBovino());
            
            String caravana = txtModificarCaravanaBovino.getText();
            Bovino bovino = dControladora.buscarBovinoCaravana(caravana);
            Date fechaIE = jDateModificarFechaIE.getDate();
            Date fechaFE = jDateModificarFechaFE.getDate();
            EstadoDelBovino estadoNuevo = (EstadoDelBovino) cboModificarEstado.getSelectedItem();

            EstadoBovino estadoBovinoViejo = new EstadoBovino(estadoViejo.getIdEstadoDelBovino(),bovinoViejo.getIdBovino(), fechaIEVieja);
            EstadoBovino estadoFechaInicio = new EstadoBovino(estadoNuevo.getIdEstadoDelBovino(),bovino.getIdBovino(), fechaIE);
            
            EstadoBovino estadoBViejo = new EstadoBovino(estadoViejo.getIdEstadoDelBovino(),bovinoViejo.getIdBovino(), fechaIEVieja,fechaFEVieja);
            EstadoBovino estadoBovinoCompleto = new EstadoBovino(estadoNuevo.getIdEstadoDelBovino(),bovino.getIdBovino(), fechaIE, fechaFE);
            
            try {
                if (jDateModificarFechaFE.getDate() == null) {
                    boolean resultado = dControladora.modificarEstadoBovinoFechaInicio(estadoFechaInicio, estadoBovinoViejo);
                    if (resultado) {

                        JOptionPane.showMessageDialog(null, "Estado Asignado al Bovino Modificado Correctamente");
                        caravana = null;
                        limpiarCajas(); // Limpiamos Caja de Texto

                        this.dispose();
                        frmEstadoConBovino estadoConBovino = new frmEstadoConBovino();
                        estadoConBovino.setVisible(true);

                    } else {
                        JOptionPane.showMessageDialog(null, "Error: No se pudo Modificar el Estado del Bovino");
                    }
                } else {
                    if (dControladora.modificarEstadoBovino(estadoBovinoCompleto, estadoBViejo)) {

                        JOptionPane.showMessageDialog(null, "Estado Asignado al Bovino Modificado Correctamente");
                        caravana = null;
                        limpiarCajas(); // Limpiamos Caja de Texto

                        this.dispose();
                        frmEstadoConBovino estadoConBovino = new frmEstadoConBovino();
                        estadoConBovino.setVisible(true);

                    } else {
                        JOptionPane.showMessageDialog(null, "Error: No se pudo Modificar el Estado del Bovino");
                    }
                }
            } catch (Exception e) {
                throw e;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese los datos faltantes");
        }


    }//GEN-LAST:event_btnModificarMouseClicked

    private void btnBuscarBovinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarBovinoMouseClicked
        frmBuscarBovino buscarBovino = new frmBuscarBovino();
        frmBuscarBovino.frmBuscar = "frmModificarEstadoConBovino";
        buscarBovino.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBuscarBovinoMouseClicked

    private void txtModificarCaravanaBovinoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModificarCaravanaBovinoKeyReleased

    }//GEN-LAST:event_txtModificarCaravanaBovinoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmModificarEstadoConBovino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmModificarEstadoConBovino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmModificarEstadoConBovino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmModificarEstadoConBovino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmModificarEstadoConBovino().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarBovino;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<Object> cboModificarEstado;
    private javax.swing.ButtonGroup grupoBotones;
    private com.toedter.calendar.JDateChooser jDateModificarFechaFE;
    private com.toedter.calendar.JDateChooser jDateModificarFechaIE;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblRCaravanaB;
    private javax.swing.JLabel lblREstado;
    private javax.swing.JLabel lblRFechaInicioE;
    private javax.swing.JTextField txtModificarCaravanaBovino;
    // End of variables declaration//GEN-END:variables
}
