/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import clases.Bovino;
import clases.Enfermedad;
import clases.Padece;
import dominio.dControladora;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import persistencia.pEnfermedad;
import static presentacion.frmModificarPadeceEnfermedad.caravana;

/**
 *
 * @author nico_
 */
public class frmModificarPadeceEnfermedad extends javax.swing.JInternalFrame {

     public static String caravana = null;
     
    /**
     * Creates new form frmModificarPadeceEnfermedad1
     */
    public frmModificarPadeceEnfermedad() {
        initComponents();        
         
        this.setTitle("MODIFICAR BOVINO ENFERMO");
        lblRCaravanaB.setVisible(false);
        lblRFechaInicioE.setVisible(false);
        lblREnfermedad.setVisible(false);
        llenarComboEnfermedad();
        
        
        if (caravana != null) {
            txtModificarCaravanaBovino.setText(caravana);
        } else {
            txtModificarCaravanaBovino.setText(frmPadeceEnfermedad.caravana);
        }

                
        jDateModificarFechaIE.setDate(frmPadeceEnfermedad.padece.getFechaInicio());
        Date fechaIE = jDateModificarFechaIE.getDate();
        jDateModificarFechaFE.setDate(frmPadeceEnfermedad.padece.getFechaFinalizacion());
        Date fechaFE = jDateModificarFechaFE.getDate();
        int idEnfermedad = frmPadeceEnfermedad.padece.getIdEnfermedad();
        Enfermedad enfermedad = dControladora.buscarEnfermedad(idEnfermedad); 
        
        cboModificarEnfermedad.getModel().setSelectedItem(enfermedad);
        cboModificarEnfermedad.setSelectedItem(enfermedad);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jDateModificarFechaIE = new com.toedter.calendar.JDateChooser();
        jDateModificarFechaFE = new com.toedter.calendar.JDateChooser();
        txtModificarCaravanaBovino = new javax.swing.JTextField();
        btnBuscarBovino = new javax.swing.JButton();
        lblRCaravanaB = new javax.swing.JLabel();
        lblRFechaInicioE = new javax.swing.JLabel();
        lblREnfermedad = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cboModificarEnfermedad = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Caravana:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 160, -1));
        jPanel2.add(jDateModificarFechaIE, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 160, 30));
        jPanel2.add(jDateModificarFechaFE, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 160, 30));
        jPanel2.add(txtModificarCaravanaBovino, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 100, 30));

        btnBuscarBovino.setText("Buscar");
        btnBuscarBovino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarBovinoMouseClicked(evt);
            }
        });
        jPanel2.add(btnBuscarBovino, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        lblRCaravanaB.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblRCaravanaB.setForeground(new java.awt.Color(0, 0, 0));
        lblRCaravanaB.setText("Requerido");
        jPanel2.add(lblRCaravanaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 120, 20));

        lblRFechaInicioE.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblRFechaInicioE.setForeground(new java.awt.Color(0, 0, 0));
        lblRFechaInicioE.setText("Requerido");
        jPanel2.add(lblRFechaInicioE, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 120, 20));

        lblREnfermedad.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblREnfermedad.setForeground(new java.awt.Color(0, 0, 0));
        lblREnfermedad.setText("Requerido");
        jPanel2.add(lblREnfermedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 120, 20));

        btnModificar.setText("Modificar");
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
        });
        jPanel2.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 90, -1));

        jLabel8.setText("Enfermedad:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel9.setText("Fecha Finalizacion de Enfermedad:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        cboModificarEnfermedad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        jPanel2.add(cboModificarEnfermedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 180, 30));

        jLabel4.setText("Fecha Comienzo de Enfermedad:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 550, 330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean validarCampos() {

        int contador = 0;
        if (txtModificarCaravanaBovino.getText().equals("")) {
            lblRCaravanaB.setVisible(true);
            contador++;
        } else {
            lblRCaravanaB.setVisible(false);
        }
        if (jDateModificarFechaIE.getDate() == null) {
            lblRFechaInicioE.setVisible(true);
            contador++;
        } else {
            lblRFechaInicioE.setVisible(false);
        }
        if (cboModificarEnfermedad.getSelectedIndex() == 0) {
            lblREnfermedad.setVisible(true);
            contador++;
        } else {
            lblREnfermedad.setVisible(false);
        }

        if (contador < 1) {
            return true;
        } else {
            return false;
        }
    }
    
    public void limpiarCajas() {

        txtModificarCaravanaBovino.setText(null);
        jDateModificarFechaIE.setDate(null);
        jDateModificarFechaFE.setDate(null);
        cboModificarEnfermedad.setSelectedIndex(0);

    }
    
    private void llenarComboEnfermedad() {

        ArrayList<Enfermedad> listaEnfermedades = pEnfermedad.listarEnfermedades();

        for (Enfermedad enfermedad : listaEnfermedades) {

            cboModificarEnfermedad.addItem(enfermedad);
        }

    }
    
    private void btnBuscarBovinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarBovinoMouseClicked
        frmBuscarBovino buscarBovino = new frmBuscarBovino();
        frmBuscarBovino.frm = "frmModificarPadeceEnfermedad";
        frmInicio.jDkPEscritorio.add(buscarBovino);
        buscarBovino.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBuscarBovinoMouseClicked

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked

        if (validarCampos()) {
            String caravanaVieja = frmPadeceEnfermedad.caravana;
            Bovino bovinoViejo = dControladora.buscarBovinoCaravana(caravanaVieja);
            Date fechaIEVieja = frmPadeceEnfermedad.padece.getFechaInicio();
            Date fechaFEVieja = frmPadeceEnfermedad.padece.getFechaFinalizacion();
            Enfermedad enfermedadVieja = dControladora.buscarEnfermedad(frmPadeceEnfermedad.padece.getIdEnfermedad());

            String caravana = txtModificarCaravanaBovino.getText();
            Bovino bovino = dControladora.buscarBovinoCaravana(caravana);
            Date fechaIE = jDateModificarFechaIE.getDate();
            Date fechaFE = jDateModificarFechaFE.getDate();
            Enfermedad enfermedad = (Enfermedad) cboModificarEnfermedad.getSelectedItem();

            Padece padeceViejo = new Padece(enfermedadVieja.getIdEnfermedad(), bovinoViejo.getIdBovino(), fechaIEVieja);
            Padece padeceFechaInicio = new Padece(enfermedad.getIdEnfermedad(), bovino.getIdBovino(), fechaIE);

            Padece padeceCompleta = new Padece(enfermedad.getIdEnfermedad(), bovino.getIdBovino(), fechaIE, fechaFE);
            Padece padeceViejoFF = new Padece(enfermedadVieja.getIdEnfermedad(), bovinoViejo.getIdBovino(), fechaIEVieja,fechaFEVieja);

            try {
                if (jDateModificarFechaFE.getDate() == null) {
                    boolean resultado = dControladora.modificarPadeceFechaInicio(padeceFechaInicio, padeceViejo) ;
                    if (resultado) {

                        JOptionPane.showMessageDialog(null, "Bovino Enfermo Modificado Correctamente");
                        caravana = null;
                        limpiarCajas(); // Limpiamos Caja de Texto

                        this.dispose();
                        frmPadeceEnfermedad padeceEnfermedad = new frmPadeceEnfermedad();
                        frmInicio.jDkPEscritorio.add(padeceEnfermedad);
                        padeceEnfermedad.setVisible(true);

                    } else {
                        JOptionPane.showMessageDialog(null, "Error: No se pudo Modificar el Bovino Enfermo");
                    }
                } else {
                    if (dControladora.modificarPadece(padeceCompleta, padeceViejoFF)) {

                        JOptionPane.showMessageDialog(null, "Bovino Enfermo Modificado Correctamente");
                        caravana = null;
                        limpiarCajas(); // Limpiamos Caja de Texto

                        this.dispose();
                        frmPadeceEnfermedad padeceEnfermedad = new frmPadeceEnfermedad();
                        frmInicio.jDkPEscritorio.add(padeceEnfermedad);
                        padeceEnfermedad.setVisible(true);

                    } else {
                        JOptionPane.showMessageDialog(null, "Error: No se pudo Modificar el Bovino Enfermo");
                    }
                }
            } catch (Exception e) {
                throw e;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese los datos faltantes");
        }

    }//GEN-LAST:event_btnModificarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarBovino;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<Object> cboModificarEnfermedad;
    private com.toedter.calendar.JDateChooser jDateModificarFechaFE;
    private com.toedter.calendar.JDateChooser jDateModificarFechaIE;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblRCaravanaB;
    private javax.swing.JLabel lblREnfermedad;
    private javax.swing.JLabel lblRFechaInicioE;
    private javax.swing.JTextField txtModificarCaravanaBovino;
    // End of variables declaration//GEN-END:variables
}
