/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import clases.EstadoDelBovino;
import dominio.dControladora;
import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.JOptionPane;

/**
 *
 * @author nico_
 */
public class frmModificarEstadoDelBovino extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmModificarEstadoDelBovino1
     */
    public frmModificarEstadoDelBovino() {
        initComponents();
        
       
        this.setTitle("MODIFICAR ESTADO");

        EstadoDelBovino estado = dControladora.buscarEstadoDelBovino(frmEstadoDelBovino.idEstado);

        txtModificarNombreDelEstado.setText(estado.getEstado());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtModificarNombreDelEstado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnModificarEstado = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modificar Estado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 12))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(txtModificarNombreDelEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 210, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Estado:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 160, -1));

        btnModificarEstado.setText("Modificar");
        btnModificarEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarEstadoMouseClicked(evt);
            }
        });
        jPanel2.add(btnModificarEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 380, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void limpiarCajas() {

        txtModificarNombreDelEstado.setText(null);

    }
    
    private void btnModificarEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarEstadoMouseClicked

        String nombreEstado = txtModificarNombreDelEstado.getText();
        int idEstado = frmEstadoDelBovino.idEstado;

        EstadoDelBovino estado = new EstadoDelBovino(nombreEstado);

        try {

            if (txtModificarNombreDelEstado.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Debe Ingresar el Estado Nuevo");
            } else {
                boolean resultado = dControladora.modificarEstadoDelBovino(idEstado, estado);
                if (resultado) {

                    JOptionPane.showMessageDialog(null, "Estado Modificado Correctamente");

                    limpiarCajas(); // Limpiamos Caja de Texto

                    this.dispose();
                    frmEstadoDelBovino frmEstado = new frmEstadoDelBovino();
                    frmInicio.jDkPEscritorio.add(frmEstado);
                    frmEstado.setVisible(true);

                } else {
                    JOptionPane.showMessageDialog(null, "Error: No se pudo Modificar el Estado");
                }
            }
        } catch (Exception e) {
            throw e;
        }
    }//GEN-LAST:event_btnModificarEstadoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificarEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtModificarNombreDelEstado;
    // End of variables declaration//GEN-END:variables
}
