/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import clases.Bovino;
import clases.EstadoBovino;
import clases.EstadoDelBovino;
import dominio.dControladora;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import persistencia.pEstadoDelBovino;
import static presentacion.frmModificarEstadoConBovino.caravana;

/**
 *
 * @author nico_
 */
public class frmModificarEstadoConBovino extends javax.swing.JInternalFrame {

    public static String caravana = null;

    /**
     * Creates new form frmModificarEstadoConBovino1
     */
    public frmModificarEstadoConBovino() {
        initComponents();

        this.setSize(frmInicio.jDkPEscritorio.getWidth(), frmInicio.jDkPEscritorio.getHeight());
        this.setTitle("MODIFICAR ESTADO DEL BOVINO");
        lblRCaravanaB.setVisible(false);
        lblRFechaInicioE.setVisible(false);
        lblREstado.setVisible(false);
        llenarComboEstado();

        if (caravana != null) {
            txtModificarCaravanaBovino.setText(caravana);
        } else {
            txtModificarCaravanaBovino.setText(frmEstadoConBovino.caravana);
        }

        EstadoBovino estadoBovino = frmEstadoConBovino.estadoBovino;

        jDateModificarFechaIE.setDate(estadoBovino.getFechaInicio());
        Date fechaIE = jDateModificarFechaIE.getDate();
        jDateModificarFechaFE.setDate(estadoBovino.getFechaFinalizacion());
        Date fechaFE = jDateModificarFechaFE.getDate();
        int idEstado = estadoBovino.getIdEstadoDelBovino();
        EstadoDelBovino estadoDelBovino = dControladora.buscarEstadoDelBovino(idEstado);

        cboModificarEstado.getModel().setSelectedItem(estadoDelBovino);
        cboModificarEstado.setSelectedItem(estadoDelBovino);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jDateModificarFechaIE = new com.toedter.calendar.JDateChooser();
        jDateModificarFechaFE = new com.toedter.calendar.JDateChooser();
        txtModificarCaravanaBovino = new javax.swing.JTextField();
        btnBuscarBovino = new javax.swing.JButton();
        lblRCaravanaB = new javax.swing.JLabel();
        lblRFechaInicioE = new javax.swing.JLabel();
        lblREstado = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cboModificarEstado = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(54, 67, 114));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel2.setBackground(new java.awt.Color(133, 146, 158));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Caravana:");

        txtModificarCaravanaBovino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtModificarCaravanaBovinoKeyReleased(evt);
            }
        });

        btnBuscarBovino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar16px.png"))); // NOI18N
        btnBuscarBovino.setText("Buscar");
        btnBuscarBovino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarBovinoMouseClicked(evt);
            }
        });

        lblRCaravanaB.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblRCaravanaB.setForeground(new java.awt.Color(0, 0, 0));
        lblRCaravanaB.setText("Requerido");

        lblRFechaInicioE.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblRFechaInicioE.setForeground(new java.awt.Color(0, 0, 0));
        lblRFechaInicioE.setText("Requerido");

        lblREstado.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblREstado.setForeground(new java.awt.Color(0, 0, 0));
        lblREstado.setText("Requerido");

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar16px.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
        });

        jLabel8.setText("Estado:");

        jLabel9.setText("Fecha Finalizacion de Estado:");

        cboModificarEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));

        jLabel4.setText("Fecha Comienzo de Estado:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblREstado, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificar))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtModificarCaravanaBovino, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnBuscarBovino))
                            .addComponent(lblRCaravanaB, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(cboModificarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jDateModificarFechaIE, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRFechaInicioE, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jDateModificarFechaFE, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(182, 182, 182))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtModificarCaravanaBovino, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarBovino)
                    .addComponent(jDateModificarFechaIE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRCaravanaB, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRFechaInicioE, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboModificarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateModificarFechaFE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(lblREstado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean validarCampos() {

        int contador = 0;
        if (txtModificarCaravanaBovino.getText().equals("")) {
            lblRCaravanaB.setVisible(true);
            contador++;
        } else {
            lblRCaravanaB.setVisible(false);
        }
        if (jDateModificarFechaIE.getDate() == null) {
            lblRFechaInicioE.setVisible(true);
            contador++;
        } else {
            lblRFechaInicioE.setVisible(false);
        }
        if (cboModificarEstado.getSelectedIndex() == 0) {
            lblREstado.setVisible(true);
            contador++;
        } else {
            lblREstado.setVisible(false);
        }

        if (contador < 1) {
            return true;
        } else {
            return false;
        }
    }

    public void limpiarCajas() {

        txtModificarCaravanaBovino.setText(null);
        jDateModificarFechaIE.setDate(null);
        jDateModificarFechaFE.setDate(null);
        cboModificarEstado.setSelectedIndex(0);

    }

    private void llenarComboEstado() {

        ArrayList<EstadoDelBovino> listaEstados = pEstadoDelBovino.listarEstadosDelBovino();

        for (EstadoDelBovino estado : listaEstados) {

            cboModificarEstado.addItem(estado);
        }

    }

    private void txtModificarCaravanaBovinoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModificarCaravanaBovinoKeyReleased

    }//GEN-LAST:event_txtModificarCaravanaBovinoKeyReleased

    private void btnBuscarBovinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarBovinoMouseClicked
        frmBuscarBovino buscarBovino = new frmBuscarBovino();
        frmBuscarBovino.frm = "frmModificarEstadoConBovino";
        frmInicio.jDkPEscritorio.add(buscarBovino);
        buscarBovino.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBuscarBovinoMouseClicked

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked

        if (validarCampos()) {

            EstadoBovino estadoBovino = frmEstadoConBovino.estadoBovino;

            String caravanaVieja = frmEstadoConBovino.caravana;
            Bovino bovinoViejo = dControladora.buscarBovinoCaravana(caravanaVieja);
            Date fechaIEVieja = estadoBovino.getFechaInicio();
            Date fechaFEVieja = estadoBovino.getFechaFinalizacion();
            EstadoDelBovino estadoViejo = dControladora.buscarEstadoDelBovino(estadoBovino.getIdEstadoDelBovino());

            String caravana = txtModificarCaravanaBovino.getText();
            Bovino bovino = dControladora.buscarBovinoCaravana(caravana);
            Date fechaIE = jDateModificarFechaIE.getDate();
            Date fechaFE = jDateModificarFechaFE.getDate();
            EstadoDelBovino estadoNuevo = (EstadoDelBovino) cboModificarEstado.getSelectedItem();

            EstadoBovino estadoBovinoViejo = new EstadoBovino(estadoViejo.getIdEstadoDelBovino(), bovinoViejo.getIdBovino(), fechaIEVieja);
            EstadoBovino estadoFechaInicio = new EstadoBovino(estadoNuevo.getIdEstadoDelBovino(), bovino.getIdBovino(), fechaIE);

            EstadoBovino estadoBViejo = new EstadoBovino(estadoViejo.getIdEstadoDelBovino(), bovinoViejo.getIdBovino(), fechaIEVieja, fechaFEVieja);
            EstadoBovino estadoBovinoCompleto = new EstadoBovino(estadoNuevo.getIdEstadoDelBovino(), bovino.getIdBovino(), fechaIE, fechaFE);

            try {
                if (jDateModificarFechaFE.getDate() == null) {
                    boolean resultado = dControladora.modificarEstadoBovinoFechaInicio(estadoFechaInicio, estadoBovinoViejo);
                    if (resultado) {

                        JOptionPane.showMessageDialog(null, "Estado Asignado al Bovino Modificado Correctamente");
                        caravana = null;
                        limpiarCajas(); // Limpiamos Caja de Texto

                        this.dispose();
                        frmEstadoConBovino estadoConBovino = new frmEstadoConBovino();
                        frmInicio.jDkPEscritorio.add(estadoConBovino);
                        estadoConBovino.setVisible(true);

                    } else {
                        JOptionPane.showMessageDialog(null, "Error: No se pudo Modificar el Estado del Bovino");
                    }
                } else if (jDateModificarFechaFE.getDate().before(fechaIE)) {
                    
                    JOptionPane.showMessageDialog(null, "La Fecha de Finalización debe ser Mayor o Igual a la de Inicio");
                    
                } else {
                    if (dControladora.modificarEstadoBovino(estadoBovinoCompleto, estadoBViejo)) {

                        JOptionPane.showMessageDialog(null, "Estado Asignado al Bovino Modificado Correctamente");
                        caravana = null;
                        limpiarCajas(); // Limpiamos Caja de Texto

                        this.dispose();
                        frmEstadoConBovino estadoConBovino = new frmEstadoConBovino();
                        frmInicio.jDkPEscritorio.add(estadoConBovino);
                        estadoConBovino.setVisible(true);

                    } else {
                        JOptionPane.showMessageDialog(null, "Error: No se pudo Modificar el Estado del Bovino");
                    }
                }
            } catch (Exception e) {
                throw e;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese los datos faltantes");
        }

    }//GEN-LAST:event_btnModificarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarBovino;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<Object> cboModificarEstado;
    private com.toedter.calendar.JDateChooser jDateModificarFechaFE;
    private com.toedter.calendar.JDateChooser jDateModificarFechaIE;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblRCaravanaB;
    private javax.swing.JLabel lblREstado;
    private javax.swing.JLabel lblRFechaInicioE;
    private javax.swing.JTextField txtModificarCaravanaBovino;
    // End of variables declaration//GEN-END:variables
}
