/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import clases.BotonesTabla;
import clases.Bovino;
import clases.Enfermedad;
import clases.Hembra;
import clases.Padece;
import clases.Produccion;
import clases.Tratamiento;
import dominio.dControladora;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.pEnfermedad;

/**
 *
 * @author nico_
 */
public class frmTratamiento extends javax.swing.JFrame {

    JButton modificar = new JButton("Modificar"); // Creamos los botones para la tabla
    JButton eliminar = new JButton("Eliminar");

    public static int columna, row; // Metodo para cuando hacemos click en los botones

    public frmTratamiento() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH); // Maximisa la ventana 
        this.setTitle("TRATAMIENTO ENFERMEDAD");
        modificar.setName("btnModificar");
        eliminar.setName("btnEliminar");
        lblRFechaInicioT.setVisible(false);
        

        
       /* if (txtCaravanaBovino.getText().isEmpty()) {
            actualizarTabla();

        } else {
            actualizarTablaTratamientoB();
        }*/

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotones = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTratamiento = new javax.swing.JTable();
        jDateFechaInicioT = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        btnBuscarBovino = new javax.swing.JButton();
        lblRFechaInicioT = new javax.swing.JLabel();
        jDateFechaFinalizacionT = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDetalle = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableTratamiento = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column){
                return false;
            }};
            jTableTratamiento.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
            ));
            jTableTratamiento.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jTableTratamientoMouseClicked(evt);
                }
            });
            jScrollPane1.setViewportView(jTableTratamiento);

            jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 910, 220));
            jPanel1.add(jDateFechaInicioT, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 160, 30));

            jLabel4.setText("Fecha Comienzo de Tratamiento:");
            jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

            btnIngresar.setText("Ingresar");
            btnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    btnIngresarMouseClicked(evt);
                }
            });
            jPanel1.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 90, -1));

            btnBuscarBovino.setText("Buscar");
            btnBuscarBovino.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    btnBuscarBovinoMouseClicked(evt);
                }
            });
            jPanel1.add(btnBuscarBovino, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, -1));

            lblRFechaInicioT.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
            lblRFechaInicioT.setForeground(new java.awt.Color(0, 0, 0));
            lblRFechaInicioT.setText("Requerido");
            jPanel1.add(lblRFechaInicioT, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 120, 20));
            jPanel1.add(jDateFechaFinalizacionT, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 160, 30));

            jLabel8.setText("Detalle:");
            jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

            jLabel9.setText("Fecha Finalizacion de Tratamiento:");
            jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

            jTextAreaDetalle.setColumns(20);
            jTextAreaDetalle.setRows(5);
            jScrollPane2.setViewportView(jTextAreaDetalle);

            jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 400, -1));

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1013, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    public boolean validarCampos() {

        int contador = 0;
        if (jDateFechaInicioT.getDate() == null){lblRFechaInicioT.setVisible(true);contador++;} else{lblRFechaInicioT.setVisible(false);}
               
        if (contador < 1) {
            return true;
        } else {
            return false;
        }
    }

    public void limpiarCajas() {
        
        jDateFechaInicioT.setDate(null);
        jDateFechaFinalizacionT.setDate(null);       
        
    }

    public void actualizarTabla() {
        jTableTratamiento.setDefaultRenderer(Object.class, new BotonesTabla());
        DefaultTableModel model = new DefaultTableModel();

        ArrayList<Tratamiento> listaTratamientos = dControladora.listarTratamientos();

        model.addColumn("ID Tratamiento");        
        model.addColumn("Caravana");
        model.addColumn("Enfermedad");        
        model.addColumn("Fecha Inicio");
        model.addColumn("Fecha Finalización");
        model.addColumn("Detalle");
        model.addColumn("Modificar ");
        model.addColumn("Eliminar ");

        for (Tratamiento t : listaTratamientos) {
            
           model.addRow(new Object[]{t.getIdTratamiento(),t.getEnfermedad().getNombre(),t.getBovino().getCaravanaBovino(),t.getFechaInicio(),t.getFechaFinalizacion(),t.getDetalle(), modificar, eliminar});
        }

        jTableTratamiento.setModel(model);
        jTableTratamiento.setRowHeight(25);
    }

    public void actualizarTablaTratamientoB() {
      /*  
        jTableTratamiento.setDefaultRenderer(Object.class, new BotonesTabla());
        DefaultTableModel model = new DefaultTableModel();

        String caravana = txtCaravanaBovino.getText();
        Bovino bovino = dControladora.buscarBovinoCaravana(caravana);

        ArrayList<Tratamiento> listaTratamientosB = dControladora.listarTratamientosBovino(bovino.getIdBovino());

        model.addColumn("ID Tratamiento");        
        model.addColumn("Caravana");
        model.addColumn("Enfermedad");        
        model.addColumn("Fecha Inicio");
        model.addColumn("Fecha Finalización");
        model.addColumn("Detalle");
        model.addColumn("Modificar ");
        model.addColumn("Eliminar ");

        for (Tratamiento t : listaTratamientosB) {
            
           model.addRow(new Object[]{t.getIdTratamiento(),t.getEnfermedad().getNombre(),t.getBovino().getCaravanaBovino(),t.getFechaInicio(),t.getFechaFinalizacion(),t.getDetalle(), modificar, eliminar});
        }

        jTableTratamiento.setModel(model);
        jTableTratamiento.setRowHeight(25);*/
    }   

    public static int idProduccion = 0;
    private void jTableTratamientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTratamientoMouseClicked
       /*
        columna = jTablePadeceEnfermedad.getColumnModel().getColumnIndexAtX(evt.getX());
        row = evt.getY() / jTablePadeceEnfermedad.getRowHeight();
        if (columna <= jTablePadeceEnfermedad.getColumnCount() && columna >= 0 && row <= jTablePadeceEnfermedad.getRowCount() && row >= 0) {
            Object objeto = jTablePadeceEnfermedad.getValueAt(row, columna);
            if (objeto instanceof JButton) {
                ((JButton) objeto).doClick();
                JButton botones = (JButton) objeto;

                if (botones.getName().equals("btnModificar")) {

                    int fila = jTablePadeceEnfermedad.getSelectedRow();

                    if (fila != -1) {
                        limpiarCajas();

                        idProduccion = (int) jTablePadeceEnfermedad.getValueAt(fila, 0);

                        this.dispose();
                        frmModificarProduccion modificarProduccion = new frmModificarProduccion();
                        modificarProduccion.setVisible(true); // Abre el formulario de Modificar la Enfermedad

                    } else {
                        JOptionPane.showMessageDialog(null, "Error: No se selecciono el Bovino a modificar");
                    }
                } else {
                    int fila = jTablePadeceEnfermedad.getSelectedRow();

                    int id = Integer.parseInt(this.jTablePadeceEnfermedad.getValueAt(fila, 0).toString());

                    try {

                        //La primera opcion seleccionada (SI) devuelve cero y la segunda (NO) devuelve uno
                        int opcion = JOptionPane.showConfirmDialog(null, "Desea Eliminar la Producción de esta Hembra?", "Eliminar Producción ", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

                        if (opcion == 0) {

                            boolean resultado = dControladora.bajaProduccion(id);

                            if (resultado) {

                                actualizarTabla();
                                limpiarCajas(); // Limpiamos Caja de Texto

                            } else {
                                JOptionPane.showMessageDialog(null, "Error: No se pudo Eliminar la Producción");
                            }

                        } else {

                            JOptionPane.showMessageDialog(null, "La Producción no se Elimino");
                        }

                    } catch (Exception e) {
                        throw e;
                    }
                }
            }
        }*/
    }//GEN-LAST:event_jTableTratamientoMouseClicked

    private void btnIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseClicked
        /*
        if (validarCampos()) {
            String caravana = txtCaravanaBovino.getText();
            Enfermedad enfermedad =  (Enfermedad)cboEnfermedad.getSelectedItem();
            String detalle = jTextAreaDetalle.getText();
            Date fechaInicioT = jDateFechaInicioT.getDate();
            Date fechaFinalizacionT = jDateFechaFinalizacionT.getDate();
            
            Bovino bovino = dControladora.buscarBovinoCaravana(caravana);

            Tratamiento tratamiento = new Tratamiento(bovino, enfermedad, detalle, fechaInicioT, fechaFinalizacionT);

            try {

                boolean resultado = dominio.dTratamiento.altaTratamientoFechaInicio(tratamiento);

                if (resultado) {

                    JOptionPane.showMessageDialog(null, "Se Ingreso Correctamente el Tratamiento al Bovino Enfermo");
                    actualizarTabla();
                    limpiarCajas(); // Limpiamos Caja de Texto

                } else {
                    JOptionPane.showMessageDialog(null, "Error: No se pudo ingresar el Tratamiento al Bovino Enfermo");
                }

            } catch (Exception e) {
                throw e;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese los datos faltantes");
        }*/
    }//GEN-LAST:event_btnIngresarMouseClicked

    private void btnBuscarBovinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarBovinoMouseClicked
        frmBuscarBovino buscarBovino = new frmBuscarBovino();

        buscarBovino.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBuscarBovinoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTratamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTratamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTratamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTratamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTratamiento().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarBovino;
    private javax.swing.JButton btnIngresar;
    private javax.swing.ButtonGroup grupoBotones;
    private com.toedter.calendar.JDateChooser jDateFechaFinalizacionT;
    private com.toedter.calendar.JDateChooser jDateFechaInicioT;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableTratamiento;
    private javax.swing.JTextArea jTextAreaDetalle;
    private javax.swing.JLabel lblRFechaInicioT;
    // End of variables declaration//GEN-END:variables
}
